# Automatically generated by Sketchware Pro
-repackageclasses
-ignorewarnings
-dontwarn
-dontnote

# Custom rules to prevent R8 RAM crash on GitHub Actions and protect heavy libraries
-keep class com.k2fsa.sherpa.onnx.** { *; }
-dontwarn com.k2fsa.sherpa.onnx.**

-keep class com.tomroush.pdfbox.** { *; }
-dontwarn com.tomroush.pdfbox.**

-keep class com.google.firebase.** { *; }
-dontwarn com.google.firebase.**
