name: Build Alpha APK (Artifact Only)

on:
  push:
    branches:
      - alpha

jobs:
  build:
    name: Build and Upload APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      - name: Build Optimized Release APK
        # assembleRelease karne se size 35-40mb ho jayega
        run: ./gradlew assembleRelease --no-daemon

      - name: Upload APK to Actions Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: VoxSherpa-Alpha-APK
          # Yeh optimized release folder se APK uthayega
          path: app/build/outputs/apk/release/*.apk
          retention-days: 5
